### ISSUE TITLE
two questions

### ISSUE THREAD

**Issue by Hogego** [misterboe/slickcarousel#18]
Hello Mr. Boe,
thank you for the nice extension. Fits almost to my need`s!
I'd like to link the slice and make a hover state on the slicks. Is this possible?
In expert-mode I have a row with 4 slicks. Only the first figurecaption is shown. But I'd like to see them all. Is there a possibility for that?

Thanks a lot 
Hoge

**Comment by misterboe** [comment]
To link the slides you can override the slick template and use the image link field. Do you know what i mean or should i give you an example? 

To the second point: Can you link me the problem? i think this could be cause due the transitions from CSS, so that only the active slide shows the caption? Is that right?

**Comment by misterboe** [comment]
Fixed in 1.0.1

**Comment by Hogego** [comment]
thank you for your quick response
as I see you already fixed the topic with the caption in the newest version

for to link of the slides an example how to change the template would be realy nice!

**Comment by Hogego** [comment]
Hello,

after doing other things fpr a while, now I’ve reached the problem with the missing link again.
Could you please tell me, how the template must be changed to work for this? That would be realy great!

Greetings

Hoge

**Comment by misterboe** [comment]
Here is an example:

In the setup.txt you can see how to create an override to use your own Templates. 

Put a copy of Slickcarousel.html in `fileadmin/slickcarousel/Templates/``

and add the link in your template.

https://gist.github.com/misterboe/5de7498e810ebd57f7bfb4d2a7abeb66
