### ISSUE TITLE
Slider height

### ISSUE THREAD

**Issue by fighterii** [misterboe/slickcarousel#19]
Hey,
first of all - thanks for the extension - i really like it, and i tried some other sliders before. Nice and easy backend config / adding of slides etc. :+1: 

Is there a way to specify the max-height of the slider? the way i see (this and most other sliders) they only adapt to 100% window width (or in your case: optional slider width). 

The reason i`m asking is, that i have images in a normal foto format (3:2). But when i integrate the slider, the image fills the whole width of my screen but the height is bigger -> not all of the slider is shown on the page. 

I tried to specify a max-height css attribute for `.slick-container` but all it does is to pull my content and the progress-bar up, it leaves the slides unchanged. 

I thought that might be possible because you said, that your ext supports image crop.

If not, i guess i have to preprocess the images and crop them before uploading

**Comment by misterboe** [comment]
hey, thanks you. 

You have two possibilities. 

1. Crop the Images inside typo3 with the crop function to a other ratio. 
2. Use the "Slick - Text" Item, which loads the images as a background, and set the height ratio in the options 

Another option is to change the CSS

<img width="1845" alt="bildschirmfoto 2016-09-07 um 08 30 06" src="https://cloud.githubusercontent.com/assets/6050140/18301988/685f6154-74d5-11e6-82f2-d9f710df58f1.png">

**Comment by fighterii** [comment]
Great - thanks for the support :)

I like the Slick-Text version.
(not always the best idea to use the expert mode first, because you think there you`ll get the best result :D)

I guess this might be a off-topic, but do you know if i can change the behaviour of the resizing? To clarify, the images now are resized by cropping the bottom. Is there a possiblity to somehow center the picture vertically? (so that a little bit of the top and a little bit of the bottom will be cropped?)

**Comment by misterboe** [comment]
This is only possible with the crop tool in typo3

**Comment by fighterii** [comment]
Okay, thanks again :)
