### ISSUE TITLE
Slick carousel with php7

### ISSUE THREAD

**Issue by Tonyt8** [misterboe/slickcarousel#20]
Hello Misterboe,

Please can you give me some advise about installing the Slick carousel extension to a Typo3 7.6.10 installation, it uses **php version 7.**
When installing the extension I receive this message.
*Your PHP version is higher than allowed. You can use PHP versions 5.4.0 - 5.6.99*
Do you know if I can safely install the extension without any issues when using php 7? I can't afford to take any risks on the installation I am currently using.

Many thanks.
Regards,
Tony

**Comment by misterboe** [comment]
I dont have any problems installing slick on php7. VHS also works with it. Are you sure that the warning is from slick? How do you install it?

**Comment by Tonyt8** [comment]
Hi,
Thanks for the quick reply.
My apologies. I've taken a better look. When first trying to install Slick carousel I thought the message was  meaning the php version was too high for Slick carousel. After trying the install again I now realize it was referring to VHS. 
Next I installed the latest version of VHS 3.0.1 then tried to install Slick carousel. Slick carousel gave the message that VHS needed to be 2.0.? and 2.4.99. I find when I try to install VHS 2.4.0 I get this message: _Your PHP version is higher than allowed. You can use PHP versions 5.4.0 - 5.6.99_.
I guess I need to ask at VHS about the version of PHP.

Do you have any advise or experience with Slick carousel 1.0.1 working with VHS 3.0.1? Will it work without any issues and without causing an issue to Typo3 in general? As before I can't any risks on this current project. 
Thanks again.

Regards,
Tony

**Comment by misterboe** [comment]
Can u please check Version 1.1.0

**Comment by Tonyt8** [comment]
Hi,
Great! Version 1.1.0 has installed perfectly. Thank you very much for updating the extension.
I will add a carousel to the content next.

Regards,
Tony
