### ISSUE TITLE
Problem with Android/iPhone standard browsers?

### ISSUE THREAD

**Issue by Uli66** [misterboe/slickcarousel#21]
Hi, thanks for this great extension!
I have implemented it on a client's website, and it works fine on all browsers I personally use. That's why I didn't notice at first that the Android standard browser doesn't show it on the phone or on the tablet, and then my client told me that it works in Safari on the iPad but not on the iPhone. (addendum: a day later it suddenly does work in Safari on the iPhone, but it still doesn't on the tablet's 'Internet' browser)
Just wondering if you have any idea what could be the problem here. Thanks in advance!
Regards
Uli

**Comment by misterboe** [comment]
We cant reproduce this issue. Can u give us an example?

**Comment by Uli66** [comment]
Hi, the problem seems to persist for a few days or so, then suddenly it works.
I have just moved a (unfinished) website to the future production server (where the slider was working on all browsers in the end), and it's ok on Safari, but not on the Android Internet browser (both Samsung Galaxy phone and tablet).
http://cms.mähroboter-online.de/ (just the 'home' page)

**Comment by misterboe** [comment]
This Problem seems not to be caused by slickcarousel.
