### ISSUE TITLE
Hyperlink does't work

### ISSUE THREAD

**Issue by kuchi62** [misterboe/slickcarousel#22]
Hi,

I use the slickcarousel 1.1.2  and it's great. But I try to set an Hyperlink on an Image and it doesn't work. On dev.ofenbau-himmelspach.de you can see 5 Sliders. Add. Extensions are powermail 3.12.0, mindshape_seo 1.0.16. 

What is the reason?

BR Jens

**Comment by misterboe** [comment]
Hi Jens, 

this is not a bug. Because of the usability on the Phone the slider should not be linked. If you want to you could override the template like here: 

https://gist.github.com/misterboe/5de7498e810ebd57f7bfb4d2a7abeb66

**Comment by kuchi62** [comment]
Thanks misterboe! This link was the solution for this Problem.
