### ISSUE TITLE
Setup.txt empty?

### ISSUE THREAD

**Issue by Enkrod** [misterboe/slickcarousel#23]
Since 1.1.3 the setup.txt is empty and I can't include static templates of the extension.

**Comment by Enkrod** [comment]
Resulting Problems: 

No Javascript / CSS included into the page: $(...).slick is not a function
No way to change constants,
No way to change RootPaths with own TypoScript

**Comment by misterboe** [comment]
I reverted the changes in version 1.2.0. Please update and test if it its fixed

**Comment by Enkrod** [comment]
FIXED. Thanks, works like a charm now.
