### ISSUE TITLE
[BUG] Option to add link to image is missing

### ISSUE THREAD

**Issue by Outdoorsman** [misterboe/slickcarousel#24]
I see that you show the field **Link** in your documentation here on GitHub...

![687474703a2f2f736e61672e67792f4673574e612e6a7067](https://user-images.githubusercontent.com/3075533/27649092-954b1ddc-5be5-11e7-8425-64c2fd5ab032.jpg)

...but I don't see that field available anywhere. I'm using Slick 2.0.0 and TYPO3 8.7.2. Here's a screenshot from my installation...

![2017-06-28_9-40-35](https://user-images.githubusercontent.com/3075533/27649284-24da9c84-5be6-11e7-87dc-bf5c4e7b5ce4.png)

**Comment by misterboe** [comment]
The Link field was removed because the sliders could not be linked. It would cause problems on touch devices if you want to "swipe" without clicking the link. 

The readme is wrong ;)

**Comment by Outdoorsman** [comment]
So what's your recommendation then for using the slider as a call to action?

**Comment by MacGyer** [comment]
Need to pull this up again.

How can I get the link field back?

Thanks in advance
