### ISSUE TITLE
Slick Centered Mode does not put in Class "slick-active"

### ISSUE THREAD

**Issue by ses2013** [misterboe/slickcarousel#29]
Typo3 9.5 slickcarousel 3.0.1 
When are in Centered Mode and eg 3 Slides to show the active Slide in the Center gets the Class "slick-current slick-active slick-center" and the one left and right should get "slick-active" which is important to do manipulations on them. But they don't.
Cheers
Stefan

**Comment by Alphatone** [comment]
Could you add more information? I tried setting up with "typo3/minimal": "^9.5", "bo/slickcarousel": "^3.0" and it seemed to work fine. Be sure to select the centered Mode option and set slides to show to 3 or more.

![bildschirmfoto 2018-10-22 um 12 42 25](https://user-images.githubusercontent.com/12185462/47288830-268a3e80-d5f8-11e8-984e-77da48d7404d.png)

![bildschirmfoto 2018-10-22 um 12 41 10](https://user-images.githubusercontent.com/12185462/47288841-2f7b1000-d5f8-11e8-9cf0-9ae31f6fe695.png)

**Comment by ses2013** [comment]
same Setup not working for me.
I can't give further Infos as it is exactly the same …
strange

**Comment by ses2013** [comment]
I disabled all features and re-enabled them ONE-BY-ONE and it only if the "infinite: Infinite looping" is enabled the Class gets written properly … can you reproduce this?

**Comment by misterboe** [comment]
@Alphatone can u check this

**Comment by Alphatone** [comment]
On it

**Comment by Alphatone** [comment]
You are right @ses2013 enabling the infinite option does in fact set `slick-active` to the neighbouring `slick-current` siblings. 

I setup this plunker to check if the behaviour is only appearing with the slick-carousel extension but it does seem like this is working as intended.
You might be interested in opening an issue over at https://github.com/kenwheeler/slick.
