### ISSUE TITLE
Hide the progress bar below the slide

### ISSUE THREAD

**Issue by pantanal93** [misterboe/slickcarousel#31]
Hello,

Is it possible to hide the progress bar below the slide? In the settings I find the possibility to hide the indicator dots, but nothing for the progress bar. Or can I do this by commenting out lines of code in any Slick Carousel configuration file?
BTW: A great extension.

Best regards
pantanal93

**Comment by misterboe** [comment]
Hi, 

there are four constants for that option 

https://github.com/misterboe/slickcarousel/blob/master/Configuration/TypoScript/constants.txt#L16

**Comment by pantanal93** [comment]
Hello misterboe,

Great, it worked perfectly. Many thanks for this prompt support.
