### ISSUE TITLE
With Slick-Export the word "Array"  appears above the slide

### ISSUE THREAD

**Issue by pantanal93** [misterboe/slickcarousel#32]
Hello misterboe,

another request: If I select the option "Randomize selected images with vhs (slower)", the word "Array" is displayed above the slide in the frontend (Randomized selected images works). With the option "Random starting slide (pseudo random)" it doesn't appear.
What could be the reason?

Typo3 8.7.22, Slick Carousel 2.0.0

Best regards
pantanal93

![snap8](https://user-images.githubusercontent.com/46625482/51245742-e1707100-1988-11e9-93a0-8575f755670f.jpg)

**Comment by MarketingAllrounder** [comment]
Sid you find a solution for this issue? I have the same problem.

**Comment by misterboe** [comment]
If this is still a problem please reopne the ticket.

**Comment by pantanal93** [comment]
I just checked it: it is no longer a problem - although the Slick Carousel version is unchanged, only Typo3 is currently 8.7.30..
