### ISSUE TITLE
Not working on TYPO3 9.5

### ISSUE THREAD

**Issue by M4rt1n17** [misterboe/slickcarousel#33]
System:
TYPO3 9.5.3
PHP 7.3.1
vhs 5.1.1 (also tested 5.1.0)
slickcarousel 3.0.1

Constants are at standard.

Whats working:

Slick - Basic (No, no pictures shown)
Slick - Synced (Yes, but no Thumbnail, just distored pictures)
Slick - Text (Just Text is shown)
Slick - Expert (No, no pictures shown)

I spend my hours switching every configuration to make it work. Without success.
I think at Basic, Text, & Expert this is a LazyLoad issue? Is there a option to disable this?

At Synced everything gets shown but the carousel down, where I can click the thumbnails (which are not working) is very very huge.

I will show pictures after I replaced the pictures with sample pictures.
Croping pictures also is not working....

Also my TYPO-Log is not showing errors, dev-consol is also not showing any errors.

**Comment by M4rt1n17** [comment]
This is how Slick Synced looks at my page.

![zoom normal](https://user-images.githubusercontent.com/17692860/51355947-049a3e00-1ab9-11e9-8eee-f9ce7908e215.PNG)
![zoom normal2](https://user-images.githubusercontent.com/17692860/51355945-049a3e00-1ab9-11e9-8af0-fbf77a107e6e.PNG)

I zoomed a bit back to show the whole thing..
![zoom max](https://user-images.githubusercontent.com/17692860/51355946-049a3e00-1ab9-11e9-9d5f-b7815cc541cf.PNG)

Yes the pictures I use are big, but that should not be a problem. Crop is not working btw.

**Comment by M4rt1n17** [comment]
Sorry just realized that I was missing Imagick.
After installation of Imagick everything is working at SLICK - SYNCED.
Rest is still not showing any pictures (but they are in the HTML DOM)

**Comment by misterboe** [comment]
Could not be reproduced
