### ISSUE TITLE
pi_flexform not shown

### ISSUE THREAD

**Issue by buepro** [misterboe/slickcarousel#35]
Under TYPO3 9.4 I faced an issue with the pi_flexform not beeing shown in the backend resulting in a JS-error in the FE. When adapting the TCA as mentioned below it was fine.

Fix:

`unset($GLOBALS['TCA']['tt_content']['columns']['pi_flexform']['config']['ds'][',slickcarouselbasic']);
unset($GLOBALS['TCA']['tt_content']['columns']['pi_flexform']['config']['ds'][',slickcarouselsync']);
unset($GLOBALS['TCA']['tt_content']['columns']['pi_flexform']['config']['ds'][',slickcarousel']);
unset($GLOBALS['TCA']['tt_content']['columns']['pi_flexform']['config']['ds'][',slickcarouselbgimg']);

\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addPiFlexFormValue(
    '*',
    'FILE:EXT:slickcarousel/Configuration/FlexForms/slick-basic.xml',
    'slickcarouselbasic'
);
\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addPiFlexFormValue(
    '*',
    'FILE:EXT:slickcarousel/Configuration/FlexForms/slick-synked.xml',
    'slickcarouselsync'
);
\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addPiFlexFormValue(
    '*',
    'FILE:EXT:slickcarousel/Configuration/FlexForms/slick-responsive.xml',
    'slickcarousel'
);
\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addPiFlexFormValue(
    '*',
    'FILE:EXT:slickcarousel/Configuration/FlexForms/slick-responsive.xml',
    'slickcarouselbgimg'
);`

**Comment by misterboe** [comment]
Fixed in #36
