### ISSUE TITLE
Backend Image Link not visible

### ISSUE THREAD

**Issue by geodem** [misterboe/slickcarousel#37]
Hello,

In Slickcarousel version 1.2.0 with Typo3 7.6 I was able to override the template paths to add the image link functionality (https://gist.github.com/misterboe/5de7498e810ebd57f7bfb4d2a7abeb66).

In Slickcarousel 3.0.2 / Typo3 9.5 the image link field seems to be hidden. How can I add it back? Since this is a usefull feature is there a reason why it is not implemented by default?

Thanks!
Georg

**Comment by geodem** [comment]
I see this issue was already discussed here: https://github.com/misterboe/slickcarousel/issues/24 however with no solution. If there is a problem on mobile devices with swiping the images an option would be to add a link field to Slick Text --> Headline, Subline, Link, Image

**Comment by misterboe** [comment]
Feel free to send a PR for that, actually this will not be changed from my side.

**Comment by csguevara** [comment]
Hallo, it is possible to reactivate the link or optionally, to activate it globally. Constant option (enable / disable link)
Gruss ;-)
