### ISSUE TITLE
TYPO3 8.7 "typo3/cms" dependency

### ISSUE THREAD

**Issue by instruccionesaldorso** [misterboe/slickcarousel#38]
Branch for TYPO3 8.7 for this extension depends (through composer) on "typo3/cms" package.
Could you please change it to "typo3/cms-core"?
This is the only extension we have over our system that blocks us to split over our composer.json the core packages and still depends on "typo3/cms" as a block, which should be not used anymore.

**Comment by misterboe** [comment]
@instruccionesaldorso should be fixed

**Comment by instruccionesaldorso** [comment]
Thank you very much!

**Comment by instruccionesaldorso** [comment]
Could you reopen the ticket, please?
You did this for latest version compatible with TYPO3 9.5 but this must be done for TYPO3 8.7 version as well.
There should be a new 2.0.1 release, I guess, with that change.
Could you apply it, please?

**Comment by misterboe** [comment]
This was done in e75e51386adacb8f99ccf181885e01a957be0c74 at branch 8.x 
If you using composer based setup try 'dev-8.x' as branch

**Comment by instruccionesaldorso** [comment]
Ah, ok, sorry, I didn't see that. You're totally right! Thanks!
I changed my composer.json to use that branch.
