### ISSUE TITLE
Text elements in a container and more

### ISSUE THREAD

**Issue by Hobokens** [misterboe/slickcarousel#4]
Hi,
nice new extension, thanks for it!
I have two question:
a) Do you plan to integrate the option to use text elements in a container?
b) With slick you have the possibility to synchronize two independant sliders with each other. What do you think about this feature for TYPO3?

**Comment by misterboe** [comment]
b: its already in there > https://github.com/misterboe/slickcarousel/tree/master#slick---synced

a: how do you think should text be integrated? do you have a graphical example?

**Comment by Hobokens** [comment]
here you have an example made without TYPO3: Two different sliders (an image slider + a text slider) synchronised

http://www.supervision-wuerzburg.de/test/

**Comment by misterboe** [comment]
ok, i will think about what will be the best way to have these options.

**Comment by Hobokens** [comment]
great!

**Comment by misterboe** [comment]
Actually we are not going to integrate this feature.
