### ISSUE TITLE
compatibility with TYPO3 10?

### ISSUE THREAD

**Issue by SvenJuergens** [misterboe/slickcarousel#40]
Hi,
are there plans for a compatible version with TYPO3 10?

kind regards
Sven

**Comment by misterboe** [comment]
Hi Sven, 
actually it's not planned to create a TYPO3 v10 compatible version. I don't know if that really makes sense because slickslider js itselfs seems also not to be maintained i the last time.

**Comment by SvenJuergens** [comment]
Hi Boris,

this is a pity, because even if Slick itself will not be developed further, TYPO3 itself will. :)
So it's a pity that you can't use the extension with the new TYPO3 version anymore, especially if you make updates :) Would you take Pull Request?

**Comment by misterboe** [comment]
Sure PR are welcome.

**Comment by SvenJuergens** [comment]
Hi @misterboe , can you already say when you will have time for an update?

**Comment by misterboe** [comment]
@SvenJuergens sorry - just saw the open PR. Will test and merge it as soon as possible

**Comment by SvenJuergens** [comment]
@misterboe all right, thanks a lot :)

**Comment by SvenJuergens** [comment]
@misterboe hi do you know approximately when you will find time for this?

**Comment by felixgabler** [comment]
Any updates? Would be greatly appreciated to have this compatible

**Comment by misterboe** [comment]
Hey - could you try latest master branch an report bugs for 10LTS @SvenJuergens  @felixgabler

**Comment by SvenJuergens** [comment]
hi @misterboe 
In the pull request I have already listed all the things that have caused me problems in connection with v10 ... and fixed.

**Comment by misterboe** [comment]
@SvenJuergens just merged it.

**Comment by SvenJuergens** [comment]
@misterboe thanks a lot.

**Comment by misterboe** [comment]
Will release to TER soon
