### ISSUE TITLE
Adding a working Link in Figcaption

### ISSUE THREAD

**Issue by MichaelM84** [misterboe/slickcarousel#43]
I was trying to add Html Code for a Link or a Button into the Description of a single image inside the carousel. Unfortunately the HTML is rendered as Text in the frontend. How can I change the rendering method of Description Content to make it work?

Thanks
Michael

**Comment by Alphatone** [comment]
You could change `<figcaption>{file.description}</figcaption>` to `<figcaption>{file.description -> f:format.raw()}</figcaption>`.

https://docs.typo3.org/other/typo3/view-helper-reference/9.5/en-us/typo3fluid/fluid/latest/Format/Raw.html

Depending on which template you use, override the file in slickcarousel/Resources/Private/Templates/

**Comment by MichaelM84** [comment]
This worked perfect! Thank you so much!

**Comment by MichaelM84** [comment]
This worked perfect! Thank you so much!

**Comment by MichaelM84** [comment]
This worked perfect! Thank you so much!

**Comment by MichaelM84** [comment]
This worked perfect! Thank you so much!

**Comment by MichaelM84** [comment]
This worked perfect! Thank you so much!

**Comment by MichaelM84** [comment]
This worked perfect! Thank you so much!

**Comment by MichaelM84** [comment]
This worked perfect! Thank you so much!

**Comment by MichaelM84** [comment]
This worked perfect! Thank you so much!

**Comment by MichaelM84** [comment]
This worked perfect! Thank you so much!

**Comment by MichaelM84** [comment]
This worked perfect! Thank you so much!

**Comment by MichaelM84** [comment]
This worked perfect! Thank you so much!
