### ISSUE TITLE
TYPO3 v11 compatibility

### ISSUE THREAD

**Issue by featdd** [misterboe/slickcarousel#47]
Hi, will you add v11 compatibility or is this extension deprecated?

**Comment by msollmann** [comment]
I am also interested in a v11 version :-)

**Comment by hoermannklaus** [comment]
Me too

**Comment by hoermannklaus** [comment]
I made a fork and started a Upgrade branch. It did not test very much, but at first sight it seems, that there is not much todo in order to raise the compatibility to v11... I will test a bit more and make adaptions as needed.

**Comment by misterboe** [comment]
If you would send me a PR i will make a new release.

**Comment by hoermannklaus** [comment]
Ok. I still upgrade it. But when I am finished, I will make a pr. Thanks.

**Comment by misterboe** [comment]
I really appreciate that you took the work off my hands. I hope to have more time for my projects soon.

**Comment by hoermannklaus** [comment]
You are welcome. I hope I tested it well enough ;-)
I would also thank you for the extension. Really like it.
