### ISSUE TITLE
TYPO3 12 Update?

### ISSUE THREAD

**Issue by SvenJuergens** [misterboe/slickcarousel#63]
Hi @misterboe do you plan a TYPO3 12 compatible version?

**Comment by abvdveen** [comment]
👍

**Comment by misterboe** [comment]
I believe that this extension has reached the end of its lifespan. An extension whose foundation (slick.js) was last released in 2017 should not, in my opinion, be further utilized.

It would be worth considering building a new extension using Swiper.js, which provides a migration pathway. However, I regret to inform you that I will not be releasing another version of this extension.
